### ISSUE TITLE
Consider Excluding From Reconciliation by Default

### ISSUE THREAD

**Issue by knpwrs** [jhamlet/svg-react-loader#10]
I think it may be useful to provide a default implementation for `shouldComponentUpdate` as such:

```js
shouldComponentUpdate: function () {
  return false; // Exclude svg from reconciliation
}
```

I was thinking about making this available through an argument (say, `pure`) since children and props may also affect whether you want the SVG component to be reconciled. That said, there still may be a generic implementation that is possible, e.g.:

```js
shouldComponentUpdate: function (nextProps, nextState) {
  return shallowCompare(this, nextProps, nextState) && this.props.children.length === 0;
}
```

**Comment by jhamlet** [comment]
It might be better to wrap the SVG component in a higher-order component that can keep track of what props/state have changed and whether or not to render.

I intentionally [spread the provided props to the rendered SVG element](https://github.com/jhamlet/svg-react-loader/blob/master/utility/template.txt#L21) because there are so many possible variations of what may, or may not require a re-render.

If you can encapsulate them in a higher-order component, it can manage that for the specific domain that you require in your application.

Some links about higher-order components:

* https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750#.u3ldjj9qb
* http://jamesknelson.com/structuring-react-applications-higher-order-components/

(Basically, wrap a component with another that adds functionality/logic but uses the passed in component for rendering.)

**Comment by knpwrs** [comment]
Yeah, still trying to get better at recognizing opportunities for higher order components. Definitely a better solution than complicating the tools. I might still explore some options for making it automatic though.
